package main

// nigerianStates is the JRB authority seed: 36 states + FCT.
var nigerianStates = []struct {
	Code string
	Name string
}{
	{"NG-AB", "Abia State Internal Revenue Service"},
	{"NG-AD", "Adamawa State Internal Revenue Service"},
	{"NG-AK", "Akwa Ibom State Internal Revenue Service"},
	{"NG-AN", "Anambra State Internal Revenue Service"},
	{"NG-BA", "Bauchi State Board of Internal Revenue"},
	{"NG-BY", "Bayelsa State Board of Internal Revenue"},
	{"NG-BE", "Benue State Board of Internal Revenue"},
	{"NG-BO", "Borno State Board of Internal Revenue"},
	{"NG-CR", "Cross River State Internal Revenue Service"},
	{"NG-DE", "Delta State Board of Internal Revenue"},
	{"NG-EB", "Ebonyi State Board of Internal Revenue"},
	{"NG-ED", "Edo State Internal Revenue Service"},
	{"NG-EK", "Ekiti State Internal Revenue Service"},
	{"NG-EN", "Enugu State Internal Revenue Service"},
	{"NG-FC", "FCT Internal Revenue Service"},
	{"NG-GO", "Gombe State Board of Internal Revenue"},
	{"NG-IM", "Imo State Internal Revenue Service"},
	{"NG-JI", "Jigawa State Board of Internal Revenue"},
	{"NG-KD", "Kaduna State Internal Revenue Service"},
	{"NG-KN", "Kano State Board of Internal Revenue"},
	{"NG-KT", "Katsina State Board of Internal Revenue"},
	{"NG-KE", "Kebbi State Board of Internal Revenue"},
	{"NG-KO", "Kogi State Internal Revenue Service"},
	{"NG-KW", "Kwara State Internal Revenue Service"},
	{"NG-LA", "Lagos State Internal Revenue Service"},
	{"NG-NA", "Nasarawa State Board of Internal Revenue"},
	{"NG-NI", "Niger State Board of Internal Revenue"},
	{"NG-OG", "Ogun State Internal Revenue Service"},
	{"NG-ON", "Ondo State Internal Revenue Service"},
	{"NG-OS", "Osun State Internal Revenue Service"},
	{"NG-OY", "Oyo State Board of Internal Revenue"},
	{"NG-PL", "Plateau State Internal Revenue Service"},
	{"NG-RI", "Rivers State Internal Revenue Service"},
	{"NG-SO", "Sokoto State Board of Internal Revenue"},
	{"NG-TA", "Taraba State Board of Internal Revenue"},
	{"NG-YO", "Yobe State Board of Internal Revenue"},
	{"NG-ZA", "Zamfara State Board of Internal Revenue"},
}
